sudo: required
language: node_js
node_js:
- 8.5.0
addons:
  ssh_known_hosts: $DEPLOY_HOST
before_deploy:
- openssl aes-256-cbc -K $encrypted_5ba5e73ad74f_key -iv $encrypted_5ba5e73ad74f_iv
  -in id_rsa.enc -out id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
deploy:
- provider: script
  script: scripts/deploy.sh
  on:
   branch: deployToDO
env:
  global:
  - secure: TVVckmz1dJqPntmIHembMx6E3OSW+N4A9lp6Te48y4X/14WX/yFUk5nSQR2A8ijN0Ykl/hIERYSEAQ4KUbiW2qrIIFUpYXGTaIk2DoV6R2l5hU6tqG6BXb5RnIxjzO+cIElYJ1EWj35CVnH1s5PA/g2nU4sfc5inS1D57P0nzK5pzPUNuZaNvUv3Tru/BqVa9TZaUo3NBpvsKN0BUOhYIHv9XEXSVmtiPCD6tJIBKmBqV+n1FUfDqbfZMZtvYSAVktO9p1uKRaNQ/uvL2EnhYTy/WNWXK12ZyrpwjJqvijgc7p3RqE3fmha4rEvdT7nVBvgvDmW2OIawIOLlsK8XcwFQ4Gbh1jgIFpWnMSz1desD8eTgdTWxFALXrTCDhhLLoV7j9T3Q2qXuDtAaY0iirjGwnDC2+6Jzcb222STscvCG1lG24rxI7fJwnpStMF9mh0UR8kO8BadxlDjBCR7yH3ad2IYqUgwdOhyzP1TrrouJae4ILK3FKD7gkyUZ7IwFiQ5sprsCaIyiXILj8fBXQLEP0H135uLewHQRTG/ZHb+TlUzDwFJVc2iSACywhy1/O3AIm7o7O6szoteIG7WUK0xaIKdQH+BKcsHALQXHOA+GLiiySv1qllVzrSj2GOiRq250/HiJXYmxAVobsebcoNgribQFwi5+StXYYhIHV6Y=
  - secure: HuMnW0/sgDyM4g2vo91Gb4QOV9qQVTxdiT9lFnLtnsqy5S9hMnH8vpV3LqOWAez3thNhJfKSx2uZe4t6S3Um/qMHnbtngMxJBuIRx0IznVI87V1VwAEgiE6Hera6i7nABU79VUpt6yZGe0q3wxiDxJL/zH4le3vINCBh8j6d9raI5/AaauTYeiIm/6URwYEY9mnuiD9wroQ8WRHnc44n2UI6wo0nyqThlXA+2L5jrW4VJ8gGOrdIX1/a65tJxGZdFDxPZPIh/gcRl80yuTZG5b+yYs65TWX1vdzxjUVdjpYfOK/lf3D8EXJw02s7+3XfbfwJVefIHke3fdMI6PwFIY9D6d+ghgssGvZmHe8k0efsEMXRF8a+J5MFFnDOiW5ETT4vENFuhw37ziEm7MKdtZcbTjIc4M00KSwvPiH3gO+jDCk67e2aujnbAQAVIVcVFkN2/PGAnrUVQWaZNeCWiHBgYwt5BTfWKWVW3itW/pDAHqP0I5KAxdOnu+VqZXW8r7wcTtiqNfNR55teEO4zCz/oTYGl9cNPslSdqqjKzEba3H/BRQ8u3fCx8yvb8kD5vUI44xhRhIh2XIEA4qvGJN3l30H8CUl3TNejDMoJTaA7aidwKdsCcQ0rGaqIPK2ITiK4ILc35OXW83n5aVJLZeQrU3XWQpb3Nn48lQ+3b/c=
  - secure: HuwcgWBbn1dxymtnZtaWkxiGpB2fhRdyiUCSpc4hFgbmLe8XGsFQn/qmd0ogNX+6dRTH9QgrYBVdxoO0YD1hYM7HonjynA/unGvO4IUd61G7lsVm00yOYHPG+QpJm6/CcHEFNfdbrmX7BrcQUbeu7a9XtEjp/csqZ7FLoxjUJt0CM4dImc91OH0WFNEQF0CG1OoMBeBOmFZcBc5FnsCKexjUDX/lVYS01ldgZb1OH0g840EPD1p8PYZeA7oIf4rjEiTrFo+rD66ZkTuMTiGKLrSHehO0mL7X1dDfgGwUNZmzwEFxbk5Nj9fV26fEPyJbxGaHguaY5USnMTHjxELf2yXmtYYSUkQ3zgxmAa8Rq8iGc7Zw1m3m3XU+KBP0A71pv22S5HXb+ABEoKICLIuVy2bLcDQG2dyaL4ZT0zcPGiaUc+/+ZupFzJ4bQlsDjtmgwMvFaswiTlaBbmqcoZjlBm7Ukb5zhD+wASRm7Qg2ZuwIVwwUAu8jKBkZNH7Vr40VUWTl4zHlij0DGeQOWIJFqG7MfMhF+3O+XrA1mhb121NM3r+iN/mVEZooSniG2C/vE2mewiLN/wxmrUn0eevJK21pmGOvdxrLyq66cHPDqAiTmh3gm0pXl1a8BwKk1dPibfxdsB0CIyGM5bOynWR7orXclN8uiC8nyj7BSNITJKc=
