sudo: required
language: node_js
node_js:
- 8.5.0
before_deploy:
- echo -e "Host 95.85.54.211\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- mkdir build
- rsync -av $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/build --exclude=build --exclude=scripts
- tar -czf package.tgz build
- openssl aes-256-cbc -K $encrypted_5ba5e73ad74f_key -iv $encrypted_5ba5e73ad74f_iv
  -in id_rsa.enc -out id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
- scp package.tgz deploy@95.85.54.211:/home/deploy/back-dev/package/
- scp scripts/deploy.sh deploy@95.85.54.211:/home/deploy/back-dev/package/
deploy:
- provider: script
  script: scripts/startDeploy.sh
  on:
    branch: fixdeploy
env:
  global:
  - secure: TWhcJH3N2RWQcruE0HWQyUq3YnY9Eg5srKXJIOyOKXooQF2sL3LeeaKIm2M3EXcOblWOvyf/9l3OLwpCVr2QBSm7nUWuyHYpUZZzGtj4cx8Elq2vqTdxOQCjUXpHNbDhtJhUB2XUxHWu1ZRqRawHwS7rjQE8aBCMrHfXdjdBQYGdu6olxL0ZDp6O30gzNtt9lW8zEUGtzCM8pJYVcbZ8/mEIqDkJX2Evg3fOsR7jAXq71aEGiZtvRXveOU+ZbJC8bpbdqOFy20M9XeR2l3qtxDcsiw1GpC6S1c+hQUNxHGOxI/xgClFV50aLM4i3ZXQLJshHIiutbZqZzanOAbdsXhDFrg5JvbCfV3ue/7ZYd8JGFsP/GEWfqtFy1TohGDB/Fn4C4kyQ6keVBNVSYlcaGGBkhi8PUwDzk2TMCgEPFR+j3NHkeQgZk+YX7Rkn5suMWjlVHWL3o7O5O+Mn28mhNoTShinUOwQg/kP7/wZsPnAI97cT4A0577XSvaEbPrQWmCbH0des5ElzJ8pkrfk1u9ZwMzHgT2ikM1zjUiZ3lu+lNE9DJUC9n6MhJOjVbN7JrNCsnFE2mmf7gJ37cW4gTuDZW/otl57S8oDua5hdq5oc5OsIA6WKtB2uTRDwMCyWZrQYhIUbVKC8yyS9n9hiAT1iQQJfamocz54cKgVXA3g=
  - secure: cFhKPsqNZGDCTTLozdtQvkwSO3qDzA4Rm5x1QLbT0hEc+rVZXQ8y3tNZfXl6jCapANqEwDxkV+Ykonkw4TpOOh9nhmjwjdpAzV1IBqzPNb9DMBPo3S773UWQ/3a2QjQ6hDdb2YJc1Q7ZIXcSnWcAD0APJSGvbQmn5rCkGHLMO+sABqthkaqiOD3lG7EDt1A1cnMJIptXLUJyylRGBD24o+K2yi8+jMbj+QM/xFw4ZEcg7Qmz+tRfR6PtbJXNzhd18umiLaX/2/9U/TIFZ4Cj12TzGfoaRzXzdN65g3FptSbXEsU10QhMI5tVSZBA5Vb+gULV9AgR4yZvoOe+Y//SEZXK3INKUt7QcHcm3xurq4ZD8FIrxCI8dskzf7GSMXE0M7lFw0nIjAiYjJrys2sLpVclKy3eWTFx6HWRf2bvrwK1rfbmLnqVLSt/7pfQJeCw9dNsxehhk3UJKWXkU6m5m8700uQQPy8azIjGP/quR80q3xk8JjJyWdyLQecEHHIyvhk9/uSFC7W/RKcNdw5dUpUDUwsNRHcvJZeQQT2t3V41gDD9yFTs5M4AUugVGCT/tmF48+Ob28B2ZCnwFAZ7RWhizpMfDv3solNCPt4xCdcZjniH9LeAb8dgTSOpJ0/OS3aq6sVE/lpWGrKT6rYRSKULZ3+tQfSZK5uNoIGm8uA=
