sudo: required
language: node_js
node_js:
- 8.5.0
before_deploy:
- echo -e "Host 95.85.54.211\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- mkdir build
- rsync -av $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/build --exclude=build --exclude=scripts
- tar -czf package.tgz build
- openssl aes-256-cbc -K $encrypted_5ba5e73ad74f_key -iv $encrypted_5ba5e73ad74f_iv
  -in id_rsa.enc -out id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
- scp package.tgz deploy@95.85.54.211:/home/deploy/back-dev/package/
- scp scripts/deploy.sh deploy@95.85.54.211:/home/deploy/back-dev/package/
deploy:
- provider: script
  script: scripts/startDeploy.sh
  on:
    branch: develop
env:
  global:
  - secure: wgF4mx5CiKJbbG8cwF1P7I3u6TKkjorUrw7SDXDg7Ih8i8H4ZgxCruN3btI7XQKQpSn7pnu6JB9Fu1qoQy3n+DmF6ZmfuvA993d62sfaU1ddnTv0rbI6poxjbQr1JzVcSwOufy8WVws2FSyR4FVFaOZfTScSM6GK2iwLeTSG2Uov6XtXLP93HvKfm9PavozvdgYn840I8fAtyebmfhenb37FfN8DofJlZyd90Xv+Jh58nRd1iW0B81DXvLULP/7ypmEa2BAPhJFFDpno+5usMyAfWbDAdXgIFYx+Z0Lri6XgxjDKzEfuOks73aftdfws1c51B8dXE+vEWrGrpRYLxTEOR/obzxoEGS+rCfavT6A8J4v/AcdJDTwYBjwIsxilX23R5TDyJBaOhPp3hFFE++tGH6O3CY1+ZD2NX11X8lbZctwyNzvlLCTfygQRV/rBLosTZ1jxBi18nQDz0WJ/QG+IeghMdEJflrNu0vZ4yHoyBZwLZ3+GwVLlRsu5vSvqRjusDK9ZWdz27/gMTzp9ZD6mW9eQsajdxrX7+5+HJZNuUAmW2ERFAUWsTzOLMAMKd5EuwS4K4zQOVghX0TiVj8IKLRLByL/HiTQpLVB6mN/D1QpZwT7mlzda1t66rCi6Wm5MUVXPQfqg/YwCmMjpK6NoEgYoNfsm7ktvCEvnZAs=
  - secure: oCn2kr16Sw/WGaLEkXnrgaMN5dxq6KPSaAutJ6XqSBQOEgu4XfojKX8FEZ7bkORVMqSJqaWC9TvtraVTEKKzjcbrqEyWiQPLyVlKiY2PuT5fTXEYmZYQYsfLvHq5zNkDHgt+hshgQL9FGWeDyr+XebP871lZXMeUwzeyp/xetEkCI+Tja4R0tFYPPLAuQtwz5RwbKX3sgKEkDDqw7li/jcaTFFAozPpiOHsAZFyn1/C6f4cE7zD1c78fs1uriN6eGdBQav7IJwvGMmZZyK04rUSQXqkS3+YMVDfmPcnKWsfRMb/OnseSCOFIOEBUUJt0F4nUqOTs0bz6heX88f5UxjiuJ5YKRXmlXnoeVdyR2OytZaNxbq34uONe7fSEH45jQOMfXw3FKdW3ntJ4/YY7+ZUUlRuT0qMHs5yVOk3N3ihsxCPt8ps5meinnC9a5UimOSkGDEtK8errxRzCgCZv0YCNxhD/fljrv1csZrP2SzB9RlaglZgbZXQVTF1WGt7Art6+YE/TpojQcrJysayGgb8Nbtj4/DWCZLaY9dxqo+0w9DjDTZfjDav6tKUYabR9GLvgnXCWHko8tEDZXWM1PUVRCDAd90d8sIcogk1QGO370wFnsmAEhztY9+TAnGOjlFKV9mQ+bO3J+Z7oI/m9LRhAXPrMHpGYFKztesEKoy8=
