sudo: required
deploy:
  provider: heroku
  api_key:
    develop: "eba7f85a-1a3c-4e5d-b464-644c4074fc55"
  app:
    develop: platform-for-testing-back
language: node_js
node_js:
  - "8.5.0"
  services:
   - mongodb