sudo: required
language: node_js
node_js:
- 8.5.0
before_deploy:
- openssl aes-256-cbc -K $encrypted_e4348d6134f0_key -iv $encrypted_e4348d6134f0_iv
  -in development.json.enc -out config/development.json -d
- echo -e "Host 95.85.54.211\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- mkdir build
- rsync -av $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/build --exclude=build --exclude=scripts
- tar -czf package.tgz build
- openssl aes-256-cbc -K $encrypted_5ba5e73ad74f_key -iv $encrypted_5ba5e73ad74f_iv
  -in id_rsa.enc -out id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
- scp package.tgz deploy@95.85.54.211:/home/deploy/back-dev/package/
- scp scripts/deploy.sh deploy@95.85.54.211:/home/deploy/back-dev/package/
deploy:
- provider: script
  script: scripts/startDeploy.sh
  on:
    branch: fixdeploy
